yggdrash:
  node:
    seed: false
    grpc.host: "localhost"
    grpc.port: 32918
    max-peers: 25
    chain.enabled: true
    chain.gen: false

spring:
  output:
    ansi:
      enabled: always

management:
  endpoint.health.show-details: always
  health:
    elasticsearch:
      enabled: false
    diskspace:
      enabled: false
  endpoint:
    restart:
      enabled: true

spring.profiles.active: local

---

spring.profiles: local

yggdrash:
  node:
    seed-peer-list:
        "ynode://00@localhost:32918"

management.endpoints.web.exposure.include: "*"

---

spring.profiles: dev

yggdrash:
  node:
    seed-peer-list:
      - "ynode://57c6510966903044581c148bb67eb47dbbeebef1@172.16.10.159:32918"

---

spring.profiles: prod

yggdrash:
  node:
    seed-peer-list:
      - "ynode://d2a5721e80dc439385f3abc5aab0ac4ed2b1cd95@52.79.188.79:32918"


---

spring.profiles: bootstrap

yggdrash:
  node:
    seed: true
    chain.enabled: false


---

spring.profiles: master

yggdrash:
  node:
    chain.gen: true


---

spring.profiles: proxy

yggdrash:
  node:
    validator-list:
      - "ynode://77283a04b3410fe21ba5ed04c7bd3ba89e70b78c@127.0.0.1:32901"

---

spring.profiles: validator

yggdrash:
  node:
    validator: true

