logging:
  level:
    io.yggdrash: debug
    io.grpc.netty: error

yggdrash.node:
  grpc.host: "localhost"
  grpc.port: 9090
  max-peers: 25
  seed-peer-list:
  - "ynode://75bff16c22e6b38c71fd2005657827acce3dfd4a1db1cc417303e429d7da9625525ba3f1b7794e104397467f8c5a11c8e86af4ffcc0aefcdf7024013cdc0508d@localhost:9090"
  - "ynode://75bff16c22e6b38c71fd2005657827acce3dfd4a1db1cc417303e429d7da9625525ba3f1b7794e104397467f8c5a11c8e86af4ffcc0aefcdf7024013cdc0508d@localhost:9091"
