
logging:
  level:
    io.yggdrash: debug

yggdrash:
  branch:
    name-list:
    #- "yeed"
  node:
    grpc.host: "localhost"
    grpc.port: 32918
    max-peers: 25

management:
  endpoint.health.show-details: always
  health:
    diskspace:
      enabled: false
  endpoint:
    restart:
      enabled: true

spring:
  output:
    ansi:
      enabled: always


