
logging:
  level:
    io.yggdrash: info

yggdrash.node:
  grpc.host: "yggdrash-node1"
  seed-peer-list:
  - "ynode://9ea9225f0b7db3c697c0a2e09cdd65046899058d16f73378c1559d61aa3e10cd5dc9337142728f5a02faadafab2b926e2998d5bc2b62c2183fab75ca996de2ce@yggdrash-node1:32918"